### ISSUE TITLE
Typo in readme.md

### ISSUE THREAD

**Issue by sbmthakur** [derhuerst/tcp-over-websockets#1]
At line 14 it should be `tcp-over-websocket` instead of `tcp-over-websockets`.

**Comment by derhuerst** [comment]
no, [it is correct](https://github.com/derhuerst/tcp-over-websockets/blob/bbb5eb8/package.json#L7). although it's probably unintuitive, now that i think about it again.

the idea behind the name was that you tunnel a single port by running the command, not multiple ones.

**Comment by derhuerst** [comment]
You're right, there was a typo in the readme, I misunderstood what you were talking about. I fixed it in f002ca9.
