### ISSUE TITLE
Source for Public Tunneling server

### ISSUE THREAD

**Issue by as1ndu** [derhuerst/tcp-over-websockets#3]
Is there a source for the publice server, wss://tcp-over-websockets-abvntgfmzf.now.sh in case I want to run my own?

**Comment by hakre** [comment]
https://tcp-over-websockets-abvntgfmzf.now.sh/_src/ I guess, it's in the repo as well.

/e: https://github.com/derhuerst/tcp-over-websockets/blob/master/server.js

**Comment by derhuerst** [comment]
[`server.js` contains the server code](https://github.com/derhuerst/tcp-over-websockets/blob/bbb5eb814660e85ad484b4e63932b495d8dfc3a0/server.js) and [the readme explains how to run it](https://github.com/derhuerst/tcp-over-websockets/blob/bbb5eb814660e85ad484b4e63932b495d8dfc3a0/readme.md#tunneling-server).

you can also run the server by cloning the repo and running `npm start` inside (after `npm install`).

**Comment by as1ndu** [comment]
LOL I feel so stupid! but thanx!! 👍
