### ISSUE TITLE
Syntax error launching the server

### ISSUE THREAD

**Issue by vmotos** [derhuerst/tcp-over-websockets#5]
(running in Ubuntu 16.04)
tcp-over-websockets-server
/usr/local/lib/node_modules/tcp-over-websockets/server.js:44
const verifyClient = ({req}, cb) => {
                      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

**Comment by derhuerst** [comment]
What is your Node version?

**Comment by vmotos** [comment]
the version with problems was 4.8.1, however I've just tested 7.7.3 (Manjaro) and it works. May be it would be a good idea to put the NodeJS version requirement in README.

Regards

**Comment by derhuerst** [comment]
[The `package.json` contains a requirement of `>=6`](https://github.com/derhuerst/tcp-over-websockets/blob/3429ba0/package.json#L23). Actually npm should have showed a warning.

**Comment by vmotos** [comment]
Ok, perfect. Issue closed. Thank you for your replies ;)
