### ISSUE TITLE
Support tunneling to TLS socket endpoints

### ISSUE THREAD

**Issue by LoneRifle** [derhuerst/tcp-over-websockets#7]
Certain destination endpoints only accept connections using SSL/TLS. Examples include hosted Postgres services which enforce sslmode, like [Neon](https://neon.tech).

This issue therefore proposes to:
- allow the client module to request an outbound TLS socket connection to the target destination from the server module, perhaps indicated through a URL query parameter, eg. `ws://tunnel.host/target.host?protocol=tls`. This will be enabled by a certain command flag like `--tls-outbound`
- get the server module to recognise and honor such requests

I'm willing to file the PR to impl this, and have opened the issue to solicit discussion.

**Comment by derhuerst** [comment]
I don't understand how your use case is not currently covered. Can't you just establish a TLS connection within/over the tunnelled TCP connection?

**Comment by LoneRifle** [comment]
That's what I thought, and indeed, I just verified that using this package as directed would allow TLS to be used within the TCP connection. 

My particular use case involves building on top of #6 and programmatically hooking up an outbound TLSSocket to the client connection handler, using [mitm.js](https://github.com/moll/node-mitm). What I hope would have happened was for the TLSSocket to go through websockets and on to its destination, but somehow, the destination only sees a raw TCP connection.

I'll dig a bit deeper to see if I can better identify what's causing the TLS information to be lost, and will file a new issue if I find something.
